KNOWN_PREFIX=iss
CHECKOUT_MASTER_AFTER_FINISH = false

# Colours
COL_ESC_SEQ='\033'
COL_RED=$COL_ESC_SEQ'[0;31m'
COL_GRN=$COL_ESC_SEQ'[0;32m'
COL_YEL=$COL_ESC_SEQ'[0;33m'
COL_BLU=$COL_ESC_SEQ'[0;34m'
COL_MAG=$COL_ESC_SEQ'[0;35m'
COL_CYN=$COL_ESC_SEQ'[0;36m'
COL_END=$COL_ESC_SEQ'[0m'