KNOWN_PREFIX="iss"
CHECKOUT_MASTER_AFTER_FINISH = false

# Colours
COL_ESC_SEQ='\033'
COL_RED=$ESC_SEQ'[1;31m'
COL_GRN=$ESC_SEQ'[1;32m'
COL_YEL=$ESC_SEQ'[1;33m'
COL_BLU=$ESC_SEQ'[1;34m'
COL_MAG=$ESC_SEQ'[1;35m'
COL_CYN=$ESC_SEQ'[1;36m'
COL_END=$ESC_SEQ'[0m'